### ISSUE TITLE
Local files and about: URLs not supported

### ISSUE THREAD

**Issue by analpi** [IsaacSchemm/sidebar-add-custom-panel#1]
I just installed this and noticed that file:/// and about: URLs aren't supported. Any chance of this being implemented?

**Comment by IsaacSchemm** [comment]
Unfortunately, SeaMonkey only allows http, https, and ftp URLs in the sidebar (see: https://gitlab.com/seamonkey-project/seamonkey-2.53-comm/-/blob/2_53_7_final/suite/components/sidebar/nsSidebar.js)

There are probably other ways to add sidebar content through an extension, but they'd be outside the scope of this particular addon.

**Comment by analpi** [comment]
Sad day. But thanks for the response.
